### ISSUE TITLE
Some comments on the code base

### ISSUE THREAD

**Issue by ngapq-misfit** [dqhieu/HDPhoneMonitor#1]
1. DB class: Log
2. Should rename it.
3. Why user "interval" as the primary key? If its range is from 0--->23, we can only store 24 records. And if we want each point represents 30 minutes, or 15 minutes, or whatever x minutes, the old data will be invalid.
4. HDPhoneMonitor
5. Do not "public" all variables and functions. 
6. Do not mix up between "singleton" style and "static" style.
7. HDChartConfig
8. Should not use global constants. Should organize them in a struct (better scope)
9. Should use "MARK:- " to separate different parts of code in one source file.

**Comment by dqhieu** [comment]
Done! Thanks for your suggestion!
